### ISSUE TITLE
.dll extraction failing

### ISSUE THREAD

**Issue by jprokos1** [jankais3r/pyPhotoDNA#1]
I have successfully extracted the .so file through macos, but cannot seem to obtain the .dll file from FTK. When running the powershell command to extract PhotoDNAx64.dll, I am presented with the following:

```
Attached          : False
BlockSize         : 0
DevicePath        :
FileSize          : 3654756352
ImagePath         : ...\pyPhotoDNA\AD_FTK_6.3.0.iso
LogicalSectorSize : 2048
Number            :
Size              : 3654756352
StorageType       : 1
PSComputerName    :

The system cannot find the file specified. 
```
and no .dll file is extracted. Thanks for the help!

**Comment by jankais3r** [comment]
Hi, not sure what the problem could be, but it's likely not on the side of the code. Some machines have `bitsadmin` blocked for security reasons because it's often used by malware. You can always perform the steps from the batch file manually. The download step would be a good candidate, as any other method of downloading will be way faster and reliable than `bitsadmin`.

**Comment by jprokos1** [comment]
Thanks for the quick reply, I downloaded the .iso file using firefox as well and I am greeted with the same error when running [this line](https://github.com/jankais3r/pyPhotoDNA/blob/7146fdaa23a0b0b3f2f83ddbec97717c9bcfcc03/install.bat#L13) of the install.bat file. I stepped through by hand and was able to use Mount-DiskImage successfully by writing out the full path then extracted the .dll using file explorer.
Thanks again for the help, cheers

**Comment by jankais3r** [comment]
Glad to hear you got it to work.
