### ISSUE TITLE
Blacklight package not available.

### ISSUE THREAD

**Issue by donharris** [jankais3r/pyPhotoDNA#3]
Is there an update to the package and/or location available?

**Comment by donharris** [comment]
Yes, I was just looking through all of that. Thanks for the quick response!

**Comment by jankais3r** [comment]
So there is a manual way to download the Cellebrite Inspector package, but I don't see a good way to integrate this into the installer script.

Steps:
1. Create a Cellebrite account [here](https://community.cellebrite.com/s/login/SelfRegister?language=en_US)
2. Once logged-in, open JavaScript Console in your browser's DevTools and run the following code:
```javascript
var fileid = 'a4i3W000000DQyFQAW';
for (const div of document.querySelectorAll('div')) {
  if (div.textContent == 'Computer Analysis Free Tools') {
    div.parentNode.parentNode.parentNode.nextSibling.firstChild.querySelector('.product-download-wrapper').click();
    break;
  }
}

setTimeout(function () {
  var dlink = document.querySelector('.files-item__download');
  dlink.setAttribute('data-file-id', fileid);
  dlink.click();
}, 2000);
```

For whatever reason (not sure if intention or oversight) the Salesforce portal currently allows download of files that are not visible in the UI by their File ID. And File ID is sequential, so you can take one of the free tools and just increment until you get the file you need. I am not sure if this is a vulnerability in Salesforce itself or just the portal that Cellebrite built on top of it, but since Salesforce only has an invite-only bug bounty program, I am not gonna spend time figuring that out.

File IDs for different versions of Inspector are (just replace on the first line of above code snippet):
`a4i3W000000irmyQAA` 10.3
`a4i3W000000irxcQAA` 10.4
`a4i3W000000DQyFQAW` 10.5

**Comment by donharris** [comment]
I'm getting this error when trying:

Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')

**Comment by donharris** [comment]
Actually, logging in took me to their main site - you need to be at their Salesforce site: https://cellebrite.force.com/Community/s/
